### ISSUE TITLE
tags not cached if only used in relation member

### ISSUE THREAD

**Issue by chnav** [omniscale/imposm#51]
Hi,
do not know is this feature or bug:
Tags not cached if they only applied to ways/nodes, used as relation_member and option **from_member:true** being set

My import configuration
```
tables:
  waterareas_outlines:
    type: relation_member
    fields:
    - name: osm_id
      type: id
    - name: member
      type: member_id
    - name: way
      type: geometry
    - name: name
      type: string
      key: name
    - name: type
      type: mapping_value
    - name: intermittent
      type: boolint
      key: intermittent
      from_member: true
    - name: seasonal
      type: boolint
      key: seasonal
      from_member: true
    - name: area
      type: pseudoarea
    mapping:
      landuse: [basin, reservoir]
      natural: [water, wetland]
      waterway: [riverbank]
```
Example:
way https://www.openstreetmap.org/way/413958037 with _seasonal=yes_
is part of water relation https://www.openstreetmap.org/relation/6173321

After cached and imported into database, the seasonal tag is lost (always set 0).

If I change above configuration
```
tags:
  load_all: true
```
then seasonal tag is imported OK

Thanks
